In [1]:
import numpy as np

In [2]:
"Implementing the basic qutrits"
def Qutrit(j):
    Q0 = np.array([1,0,0])
    Q1 = np.array([0,1,0])
    Q2 = np.array([0,0,1])
    if j == 0:
        return(np.array([1,0,0]))
    elif j == 1:
        return(np.array([0,1,0]))
    elif j == 2:
        return(np.array([0,0,1]))
def Qutrit_register(j):
    for k in range(3):
        if j[k] == 1:
            return(k)
"A register is a list of qutrits, for example A = [[alpha,Beta,gamma],[alpha1,beta1,gamma1]]"
def Qutrit_proba(A):
    return(np.array([A[0],A[1],A[2]]))
print(Qutrit_register([1,0,0]))
Q0 = np.array([1,0,0])
Q1 = np.array([0,1,0])
Q2 = np.array([0,0,1])
"Implementing basic unities"
i = np.complex(0,1)
Id = np.array([[np.complex(1,0),np.complex(0,0),np.complex(0,0)],[np.complex(0,0),np.complex(1,0),np.complex(0,0)],[np.complex(0,0),np.complex(0,0),np.complex(1,0)]])
"Number of qudits"
q = 10

0


In [3]:
" Implementing the tensor product "
" Tensor_product for a matrice"
def tensor_product_m(A,B):
    m,n = A.shape
    p,q = B.shape
    AtensorB = np.zeros((m*p,n*q), dtype ="complex")
    i_A,j_A,i_B,j_B = 0,0,0,0
    for line in range(m*p):
        i_A,i_B = line//p , line%p
        for column in range(n*q):
            j_A,j_B = column//q , column%q
            AtensorB[line][column] = A[i_A][j_A]*B[i_B][j_B]
    return AtensorB
"Tensor product for a row"
def tensor_product_r(A,B):
    T = np.array([])
    for k in range(A.shape[0]):
        T = np.concatenate((T,A[k]*B),axis = None)
    return(T)

In [4]:
"Function that given a register gives you the correspondant vector"
def register_to_vector(A):
    vector = np.array(Qutrit(A[0]))
    for j in A[1:]:
        vector = tensor_product_r(vector,Qutrit(int(j)))
    return(vector)
# def register_to_vector_2(A):
#     vector = np.array()
"Function that given a vector gives you the correspondant register"

'Function that given a vector gives you the correspondant register'

In [5]:
def racine_3_unite(x):
    return(np.exp(np.complex(0,2*np.pi*x/3)))
print(racine_3_unite(0),racine_3_unite(1),racine_3_unite(2))

(1+0j) (-0.4999999999999998+0.8660254037844387j) (-0.5000000000000004-0.8660254037844385j)


In [6]:
" Compute the Hadamard gate"

H = 1/np.sqrt(3)*np.array([[1,1,1],
              [1,racine_3_unite(1),racine_3_unite(2)],
              [1,racine_3_unite(2),racine_3_unite(4)]], dtype ="complex")

In [7]:
"Compute the Hadamard gate acting on qutrit m, knowing that there's q qutrit"
def H_gate(m,q):
    if m == 0:
        A = H
    else :
        A = Id
    for k in range(1,q):
        if k == m:
            A = tensor_product_m(A,H)
        else : 
            A = tensor_product_m(A,Id)
    return(A)
Q = tensor_product_r(tensor_product_r(Q1,Q0),Q0)

In [8]:
"Compute the rotational gate"
def racine_3_unite_2(l,m,al,bm):
    return(np.exp((2*np.pi*i*al*bm)/(3**(m-l+1))))
"Function that given a number j, and a number of qutrits q, interpret the number as a 1 in a column of zeros, and gives you the tensor decomposition"
def number_to_tensorial_product(j,q):
    A = np.array([])
    def number_to_tensor(j,q,A):
        if q == 1 :
            A = np.concatenate((j,A),axis = None)
            return(A)
        else : 
            j1 = j//3
            j2= j%3
            A = np.concatenate((j2,A), axis = None)
            return(number_to_tensor(j1,q-1,A))
    return(number_to_tensor(j,q,A))
"Compute the rotational gate, knowing that there is q qutrits, acting on qubit l and m"
def rotational_gate(l,m,q):
    A = np.zeros((3**q,3**q), dtype = "complex")
    for j in range(3**q):
        qutrits = number_to_tensorial_product(j,q)
        A[j][j] = racine_3_unite_2(l,m,qutrits[l],qutrits[m])
    return(A)
    

In [9]:
"Compute the circuit, knowing that there are q qutrits"
"we just compute a matrix product, that we apply it to a qutrit"
def circuit(q):
    Circ = np.identity(3**q)
    for k in range(0,q):
        Circ = np.dot(Circ,H_gate(k,q))
        for j in range(k+1,q):
            Circ = np.dot(Circ,rotational_gate(k,j,q))
    return(Circ)
circuit(4)

array([[ 0.11111111+0.j        ,  0.11111111+0.j        ,
         0.11111111+0.j        , ...,  0.11111111+0.j        ,
         0.11111111+0.j        ,  0.11111111+0.j        ],
       [ 0.11111111+0.j        , -0.05555556+0.09622504j,
        -0.05555556-0.09622504j, ..., -0.04793179+0.10024082j,
        -0.06284521-0.09163056j,  0.11077699-0.00861027j],
       [ 0.11111111+0.j        , -0.05555556-0.09622504j,
        -0.05555556+0.09622504j, ..., -0.0697569 -0.08648499j,
        -0.04001975+0.10365374j,  0.10977665-0.01716875j],
       ...,
       [ 0.11111111+0.j        ,  0.11111111+0.j        ,
         0.11111111+0.j        , ...,  0.1081161 +0.02562399j,
         0.1081161 +0.02562399j,  0.1081161 +0.02562399j],
       [ 0.11111111+0.j        , -0.05555556+0.09622504j,
        -0.05555556-0.09622504j, ..., -0.0697569 +0.08648499j,
        -0.04001975-0.10365374j,  0.10977665+0.01716875j],
       [ 0.11111111+0.j        , -0.05555556-0.09622504j,
        -0.05555556+0.09622504

In [10]:
"Reverse the obtained qutrit-register"
def reverse(A):
    B = np.zeros(len(A))
    for k in range(len(A)):
        B[k] = A[len(A)-k-1]
    return(B)

In [11]:
qutrit_register = tensor_product_r(tensor_product_r(Q0,Q0),Q1)
"We compute the QFT to a qutrit register"
q = 3
def compute_QFT(q,qutrit_register):
    final_register = np.dot(circuit(q),qutrit_register)
    return(final_register)
final_register = compute_QFT(q,qutrit_register)

In [12]:
"We write the final vector as a dictionary with the square probability of each qutrit_register, but we before reverse it"
def vector_to_qutrit_probabilities(vec):
    Liste = []
    for k in range(len(vec)):
        Liste.append([reverse(number_to_tensorial_product(k,q)),vec[k]])
    return(Liste)
final_liste = vector_to_qutrit_probabilities(final_register)

In [13]:
"We write it as a final vector"
def dico_to_vector(liste_proba):
    vector = np.zeros((len(liste_proba)),dtype ="complex")
    for k in range(len(liste_proba)):
        vect = register_to_vector(liste_proba[k][0])
        vector = vector + liste_proba[k][1]*vect
    return(vector)
dico_to_vector(final_liste)

array([ 0.19245009+0.j        ,  0.19245009+0.j        ,
        0.19245009+0.j        ,  0.19245009+0.j        ,
        0.19245009+0.j        ,  0.19245009+0.j        ,
        0.19245009+0.j        ,  0.19245009+0.j        ,
        0.19245009+0.j        , -0.09622504+0.16666667j,
       -0.09622504+0.16666667j, -0.09622504+0.16666667j,
       -0.09622504+0.16666667j, -0.09622504+0.16666667j,
       -0.09622504+0.16666667j, -0.09622504+0.16666667j,
       -0.09622504+0.16666667j, -0.09622504+0.16666667j,
       -0.09622504-0.16666667j, -0.09622504-0.16666667j,
       -0.09622504-0.16666667j, -0.09622504-0.16666667j,
       -0.09622504-0.16666667j, -0.09622504-0.16666667j,
       -0.09622504-0.16666667j, -0.09622504-0.16666667j,
       -0.09622504-0.16666667j])

In [14]:
"Coding the measure of a qutrit"
def measure(q):
    x = np.random.random_sample()
    T = 0
    for k in range(len(q)):
        T = T + q[k]
        if x <= T:
            return(k)

In [15]:
"Coding the inverse QFT"
"Coding the inverse of a matrix"
def reverse_matrix(M):
    return(np.linalg.inv(M))
"Inverse of the Hadamard gate"
def H_inv(m,q):
    return(np.linalg.inv(H_gate(m,q)))
"Inverse of the Rotational gate"
def R_inv(l,m,q):
    return(np.linalg.inv(rotational_gate(l,m,q)))

In [16]:
"Inversing the circuit"
def circuit_inv(q):
    Circ = np.identity(3**q)
    for k in range(0,q):
        Circ = np.dot(H_inv(k,q),Circ)
        for j in range(k+1,q):
            Circ = np.dot(R_inv(k,j,q),Circ)
    return(Circ)

### Lets compute the adder


In [17]:
" Compute the Rotor Gate X "
X = np.array([[0,0,1],[1,0,0],[0,1,0]])
" Compute the inverse X gate "
X_inv = np.array([[0,1,0],[0,0,1],[1,0,0]])
" Compute the C_up_1_X gate"
def C_up_1_X():
    A = np.identity(9)
    for k in range(3,6):
        for j in range(3,6):
            A[k,j] = X[k-3,j-3]
    return(A)
" Compute the C_up_1_X_inv gate"
def C_up_1_X_inv():
    A = np.identity(9)
    for k in range(3,6):
        for j in range(3,6):
            A[k,j] = X_inv[k-3,j-3]
    return(A)
"Compute the C_up_2_X gate"
def C_up_2_X():
    A = np.identity(9)
    for k in range(6,9):
        for j in range(6,9):
            A[k,j] = X[k-6,j-6]
    return(A)
"Compute the C_up_2_X_inv gate"
def C_up_2_X_inv():
    A = np.identity(9)
    for k in range(6,9):
        for j in range(6,9):
            A[k,j] = X_inv[k-6,j-6]
    return(A)

In [29]:
"Compute the SUM gate on 2 qutrits"
"Output : matrix representing the sum gate"
# def SUM_gate(L):
#     X_f = np.linalg.matrix_power(X,L[0])
#     j_f = np.dot(X_f,Qutrit(L[1]))
#     return([L[0],Qutrit_register(j_f)])
def SUM():
    A = C_up_1_X()
    B = C_up_2_X()
    C = np.dot(A,B)
    C = np.dot(C,B)
    return(C)
"Compute the SUM_gate knowing that there is 1 upper qutrit"
SUM_gate_3_up = tensor_product_m(Id,SUM())
"Compute SUM_2 gate on 2 qutrits"
# def SUM_2gate(L):
#     X_f = np.linalg.matrix_power(X_inv,L[0])
#     j_f = np.dot(X_f,Qutrit(L[1]))
#     return([L[0],Qutrit_register(j_f)])
def SUM_2():
    A = C_up_1_X_inv()
    B = C_up_2_X_inv()
    C = np.dot(A,B)
    C = np.dot(C,B)
    return(C)
"Compute the SUM_2gate knowing that there is 1 upper qutrit"
SUM_2gate_3_up = tensor_product_m(Id,SUM_2())
Q0_Q1 = tensor_product_r(Q2,Q2)
A = np.dot(SUM(),Q0_Q1)
print(A)

[0. 0. 0. 0. 0. 0. 0. 1. 0.]


In [19]:
# "Compute the Swap gate"
# def SWAP(L):
#     return([L[1],L[0]])

In [20]:
"Compute Control_X"
"Input : the parameter c to which we will compare the first qutrit"
"Output : the final 2 qutrit-register"
# def C_X(c,L):
#     if c == L[0]:
#         j_f = np.dot(X,Qutrit(L[1]))
#         j_f = Qutrit_register(j_f)
#     else :
#         j_f = L[1]
#     return([L[0],j_f])
# print(C_X(0,[0,1]))

'Output : the final 2 qutrit-register'

In [21]:
"Compute the control Sum gate acting on 3 qutrits"
"Input : the parameter c to which we will compare the first qutrit"
# def C_SUM(c,L):
#     if c == L[0]:
#         print(L[1:])
#         F = SUM_gate(L[1:])
#         print(F)
#     else :
#         F = L[1:]
#     F.insert(0,L[0])
#     return(F)
# print(C_SUM(0,[0,1,0]))



'Input : the parameter c to which we will compare the first qutrit'

In [22]:
"Compute S_0_1"
S_0_1 = np.array([[0,1,0],[1,0,0],[0,0,1]])
"Compute S_0_2"
S_0_2 = np.array([[0,0,1],[0,1,0],[1,0,0]])
"Compute S_1_2"
S_1_2 = np.array([[1,0,0],[0,0,1],[0,1,0]])

In [23]:
"Compute the control S_0_1 gate"
# def C_S_0_1(c,L):
#     if c == L[0]:
#         j_f = np.dot(S_0_1,Qutrit(L[1]))
#         j_f = Qutrit_register(j_f)
#     else :
#         j_f = L[1]
#     return([L[0],j_f])
# print(C_S_0_1(0,[1,0]))
def C_up_0_S_0_1():
    A = np.identity(9)
    for k in range(3):
        for j in range(3):
            A[k,j] = S_0_1[k,j]
    return(A)
def C_up_0_S_0_2():
    A = np.identity(9)
    for k in range(3):
        for j in range(3):
            A[k,j] = S_0_2[k,j]
    return(A)
def C_up_1_S_1_2():
    A = np.identity(9)
    for k in range(3,6):
        for j in range(3,6):
            A[k,j] = S_1_2[k-3,j-3]
    return(A)
def C_down_0_S_0_1():
    A = np.identity(9)
    A[0,0] = 0
    A[0,3] = 1
    A[3,3] = 0
    A[3,0] = 1
    return(A)
def C_down_1_S_1_2():
    A = np.identity(9)
    A[4,4] = 0
    A[7,4] = 1
    A[4,7] = 1
    A[7,7] = 0
    return(A)
def C_down_0_S_0_2():
    A = np.identity(9)
    A[0,0] = 0
    A[0,6] = 1
    A[6,6] = 0
    A[6,0] = 1
    return(A)

In [24]:
"Compute the matrix C_down_0_S_0_1 knowing that there is 1 down qutrit"
C_down_0_S_0_1_3_down = tensor_product_m(C_down_0_S_0_1(),Id)

In [25]:
def SWAP_gate():
    A = np.identity(9)
    A = np.dot(C_up_0_S_0_1(),A)
    A = np.dot(C_down_0_S_0_1(),A)
    A = np.dot(C_up_0_S_0_1(),A)
    A = np.dot(C_up_1_S_1_2(),A)
    A = np.dot(C_down_1_S_1_2(),A)
    A = np.dot(C_up_1_S_1_2(),A)
    A = np.dot(C_up_0_S_0_2(),A)
    A = np.dot(C_down_0_S_0_2(),A)
    A = np.dot(C_up_0_S_0_2(),A)
    return(A)
"SWAP 2 qutrit knowing that there is 1 up qutrit"
SWAP_3_up = tensor_product_m(Id,SWAP_gate())
"SWAP 2 qutrit knowing that there is 1 down qutrit"
SWAP_3_down = tensor_product_m(SWAP_gate(),Id)

In [26]:
"Compute the S_00_22 gate"
S_00_22 = np.array([[0,0,0,0,0,0,0,0,1],[0,1,0,0,0,0,0,0,0],[0,0,1,0,0,0,0,0,0],[0,0,0,1,0,0,0,0,0],[0,0,0,0,1,0,0,0,0],[0,0,0,0,0,1,0,0,0],[0,0,0,0,0,0,1,0,0],[0,0,0,0,0,0,0,1,0],[1,0,0,0,0,0,0,0,0]])
print(S_00_22)
"Compute S_00_22 knowing that there is 1 up qutrit"
S_00_22_3_up = tensor_product_m(Id,S_00_22)

[[0 0 0 0 0 0 0 0 1]
 [0 1 0 0 0 0 0 0 0]
 [0 0 1 0 0 0 0 0 0]
 [0 0 0 1 0 0 0 0 0]
 [0 0 0 0 1 0 0 0 0]
 [0 0 0 0 0 1 0 0 0]
 [0 0 0 0 0 0 1 0 0]
 [0 0 0 0 0 0 0 1 0]
 [1 0 0 0 0 0 0 0 0]]


In [27]:
"Compute the Carry gate"
"Input : a 3 qutrit register in his register form : L = [c_i,a_i,b_i]"
"Output : a 3 qutrit register in his register form"
# def Carry2(L):
#     vec_1 = register_to_vector(L)
#     F = tensor_product_m(Id,S_00_22)
#     step_1 = np.dot(F,vec_1)
#     position = np.where(step_1 == 1)[0][0]
#     step_1 = number_to_tensorial_product(position,3)
#     step_1 = [int(step_1[0]),int(step_1[1]),int(step_1[2])]
#     print("step_1",step_1)
#     step_2 = SUM_gate(step_1[1:])
#     step_2.insert(0,step_1[0])
#     print("step 2",step_2)
#     step_3 = [step_2[0],step_2[2]]
#     step_3 = SUM_2gate(step_3)
#     step_3.insert(1,step_2[1])
#     print("step 3",step_3)
#     step_4 = [step_3[2],step_3[0]]
#     print("step 4.1",step_4)
#     step_4 = C_S_0_1(0,step_4)
#     step_4 = [step_4[1],step_3[1],step_4[0]]
#     print("step 4",step_4)
#     step_5 = [step_4[0],step_4[1]]
#     step_5 = SWAP(step_5)
#     step_5.insert(2,step_4[2])
#     print("step 5",step_5)
#     step_6 = [step_5[1],step_5[2]]
#     step_6 = SWAP(step_6)
#     step_6.insert(0,step_5[0])
#     return(step_6)
# print(Carry2([0,2,2]))
    
def Carry():
    A = np.identity(27)
    A = np.dot(A,S_00_22_3_up)
    A = np.dot(SUM_gate_3_up,A)
    A = np.dot(SWAP_3_down,A)
    A = np.dot(SUM_2gate_3_up,A)
    A = np.dot(SWAP_3_down,A)
    A = np.dot(SWAP_3_up,A)
    A = np.dot(C_down_0_S_0_1_3_down,A)
    A = np.dot(SWAP_3_up,A)
    A = np.dot(SWAP_3_down,A)
    A = np.dot(SWAP_3_up,A)
    return(A)
Q0_Q0_Q0 = tensor_product_r(tensor_product_r(Q0,Q2),Q2)
B = np.dot(Carry(),Q0_Q0_Q0)
position = np.where(B == 1)[0][0]
print(position)
print("new",number_to_tensorial_product(position,3))

step_1 [0, 0, 0]
step 2 [0, 0, 0]
step 3 [0, 0, 0]
step 4.1 [0, 0]
step 4 [1, 0, 0]
step 5 [0, 1, 0]
[0, 0, 1]
1
new [0. 0. 1.]


In [30]:
"Compute the ripple-carry adder"
"Input : two n qutrit register"
"Output : two n qutrit register, on the second one the sum of the previous ones"
"to_do :  reverse_qutrit_to_register_with probabilities"
"A register is a list of qutrits, for example A = [[alpha,Beta,gamma],[alpha1,beta1,gamma1]]"
def Qutrit_proba(A):
    return(np.array([A[0],A[1],A[2]]))
def ripple_carry_adder(A,B):
    c_0 = Q0
    a_0 = Qutrit_proba(A[0])
    b_0 = Qutrit_proba(B[0])
    vector_0 = tensor_product_r(c_0,tensor_product_r(a_0,b_0))
    vector_0_f = np.dot(Carry(),vector_0)
    
    
    
    